### ISSUE TITLE
First character of prefix is chopped 

### ISSUE THREAD

**Issue by zswanson** [technicallyjosh/easy-params#1]
I created a param in ParamStore with prefix `/app1/dev/key1`
When I use easy-params to list the keys, it chops off the 'a' character, in both table and plain output.

```
easy-params ls /app1/dev/ -p
Listing parameters for "/app1/dev/"
ey1
```

```
easy-params ls /app1/dev/
Listing parameters for "/app1/dev/"
+------+--------------+------------------------+
| NAME | TYPE         | LAST MODIFIED          |
+------+--------------+------------------------+
| ey1  | SecureString | 2020-06-20 01:06:28 PM |
+------+--------------+------------------------+
```
If the key was a top level item, the output seems to remove the first *two* characters instead.

**Comment by dotjoshrc** [comment]
Hey @zswanson yup my coworker actually made me aware of this if you trail with a `/`.

I'm actually currently working on a version with some additions and this specific bug fix. 

I'm basically making the parsing of the input a bit more robust to remove and add back properly. 

New version should be out today or tomorrow. I'll update ticket when new release is out!

Cool to see others use the lib :)

**Comment by dotjoshrc** [comment]
Fixed in [v0.5.1](https://github.com/technicallyjosh/easy-params/releases/tag/v0.5.1) 🎉

**Comment by zswanson** [comment]
@technicallyjosh cool, was evaluating this and a couple other tools for broader use at our office. We've avoided paramstore because as you noted, the CLI for it is pretty bad

**Comment by zswanson** [comment]
Looks like this still occurs in the case where you pass just a single `/` as the prefix search. Works as expected for prefixes like `app1/` and `/app1/` though.

```
easy-params ls /
Listing parameters for "/"
+--------------+--------------+------------------------+
| NAME         | TYPE         | LAST MODIFIED          |
+--------------+--------------+------------------------+
| pp1/dev/key1 | SecureString | 2020-06-20 01:06:28 PM |
+--------------+--------------+------------------------+
```

**Comment by dotjoshrc** [comment]
Oh interesting haha, I've never used root i suppose. Will fix it.

**Comment by dotjoshrc** [comment]
Fixed now in [v0.5.2](https://github.com/technicallyjosh/easy-params/releases/tag/v0.5.2)
